email: testing@radiumcrm.com
oauth_key: 148490173223.apps.googleusercontent.com
oauth_secret: IftxRkgtDISFDBbKBFm2Aw9K
access_token: ya29.AHES6ZSb_Pqh9RW-F6ZruqOobQoT5iWEoDUsXYsSW1l0tPs
refresh_token: 1/KU5bpLcckmUgBBgz6g66mgfCSyVrgvx6kdciswhBPEg
